// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbAdmin = "fb_admins"

// FbAdmin 后台账户表
type FbAdmin struct {
	ID            uint64 `gorm:"column:id;primaryKey" json:"id"`
	GroupID       uint64 `gorm:"column:group_id;not null;comment:用户组id" json:"group_id"`          // 用户组id
	Nickname      string `gorm:"column:nickname;not null;comment:nickname" json:"nickname"`       // nickname
	Avatar        string `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                 // 头像
	Email         string `gorm:"column:email;not null;comment:邮箱" json:"email"`                   // 邮箱
	LoginPassword string `gorm:"column:login_password;not null;comment:密码" json:"login_password"` // 密码
	LastLoginIP   string `gorm:"column:last_login_ip;not null" json:"last_login_ip"`
	LastLoginTime int64  `gorm:"column:last_login_time;not null;comment:登陆时间" json:"last_login_time"`   // 登陆时间
	Roles         string `gorm:"column:roles;not null;comment:角色" json:"roles"`                         // 角色
	Status        int32  `gorm:"column:status;not null;default:1;comment:1正常，2禁用" json:"status"`        // 1正常，2禁用
	UpdatedAt     int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`             // 修改时间
	CreatedAt     int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`             // 创建时间
	GoogleSecret  string `gorm:"column:google_secret;not null;comment:google验证密钥" json:"google_secret"` // google验证密钥
	Username      string `gorm:"column:username;not null" json:"username"`
	BindTime      int64  `gorm:"column:bind_time;not null" json:"bind_time"`
	OperatorName  string `gorm:"column:operator_name;not null" json:"operator_name"`
	CreateName    string `gorm:"column:create_name" json:"create_name"`
	PwdEditTime   int64  `gorm:"column:pwd_edit_time;not null" json:"pwd_edit_time"`
}

// TableName FbAdmin's table name
func (*FbAdmin) TableName() string {
	return TableNameFbAdmin
}
