// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbBanner = "fb_banners"

// FbBanner 轮播图
type FbBanner struct {
	ID          int64  `gorm:"column:id;primaryKey" json:"id"`
	URL         string `gorm:"column:url;comment:轮播图图片路径" json:"url"`                                         // 轮播图图片路径
	LinkType    int32  `gorm:"column:link_type;not null;default:1;comment:链接类型 1网页链接 2公网链接" json:"link_type"` // 链接类型 1网页链接 2公网链接
	LinkH5      string `gorm:"column:link_h5;not null;comment:轮播图跳转链接(H5)" json:"link_h5"`                    // 轮播图跳转链接(H5)
	LinkApp     string `gorm:"column:link_app;not null;comment:轮播图跳转链接(APP)" json:"link_app"`                 // 轮播图跳转链接(APP)
	BackColor   string `gorm:"column:back_color;not null;comment:轮播图背景色" json:"back_color"`                   // 轮播图背景色
	StartTime   int64  `gorm:"column:start_time;not null;comment:展示开始时间" json:"start_time"`                   // 展示开始时间
	EndTime     int64  `gorm:"column:end_time;not null;comment:展示结束时间" json:"end_time"`                       // 展示结束时间
	State       int32  `gorm:"column:state;not null;default:1;comment:状态 1上线 2下线" json:"state"`               // 状态 1上线 2下线
	Seq         int32  `gorm:"column:seq;not null;comment:排序" json:"seq"`                                     // 排序
	Ty          string `gorm:"column:ty" json:"ty"`
	Category    string `gorm:"column:category" json:"category"`
	Remark      string `gorm:"column:remark;not null;comment:用途说明" json:"remark"`                          // 用途说明
	IsDelete    int32  `gorm:"column:is_delete;not null;default:2;comment:删除状态 1已删除 2正常" json:"is_delete"` // 删除状态 1已删除 2正常
	CreatedAt   int32  `gorm:"column:created_at;not null;comment:添加时间" json:"created_at"`                  // 添加时间
	CreatedUID  int64  `gorm:"column:created_uid;not null;comment:创建人uid" json:"created_uid"`              // 创建人uid
	CreatedName string `gorm:"column:created_name;not null;comment:创建人名" json:"created_name"`              // 创建人名
	UpdatedAt   int64  `gorm:"column:updated_at;not null;comment:维护时间" json:"updated_at"`                  // 维护时间
	UpdatedUID  int64  `gorm:"column:updated_uid;not null;comment:维护人uid" json:"updated_uid"`              // 维护人uid
	UpdatedName string `gorm:"column:updated_name;not null;comment:维护人名" json:"updated_name"`              // 维护人名
	Content     string `gorm:"column:content" json:"content"`
}

// TableName FbBanner's table name
func (*FbBanner) TableName() string {
	return TableNameFbBanner
}
