// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbDailyVenueReport = "fb_daily_venue_report"

// FbDailyVenueReport 场馆业绩表
type FbDailyVenueReport struct {
	ID                int64  `gorm:"column:id;primaryKey" json:"id"`
	Day               int32  `gorm:"column:day;not null;comment:数据日期" json:"day"`                                           // 数据日期
	GameName          string `gorm:"column:game_name;not null;comment:第三方游戏名称" json:"game_name"`                            // 第三方游戏名称
	GameCode          string `gorm:"column:game_code;not null;comment:第三方游戏名称编码" json:"game_code"`                          // 第三方游戏名称编码
	PlatformName      string `gorm:"column:platform_name;not null;comment:厂商名称" json:"platform_name"`                       // 厂商名称
	PlatformID        string `gorm:"column:platform_id;not null;comment:厂商id" json:"platform_id"`                           // 厂商id
	ActvNum           int32  `gorm:"column:actv_num;not null;comment:活跃人数(有效)" json:"actv_num"`                             // 活跃人数(有效)
	VenueName         string `gorm:"column:venue_name;not null;comment:场馆名称" json:"venue_name"`                             // 场馆名称
	VenueType         int32  `gorm:"column:venue_type;not null;comment:场馆类型" json:"venue_type"`                             // 场馆类型
	TotalBillNum      int32  `gorm:"column:total_bill_num;not null;comment:总注单数" json:"total_bill_num"`                     // 总注单数
	TotalBetAmount    string `gorm:"column:total_bet_amount;not null;default:0;comment:总有效投注额(有效)" json:"total_bet_amount"` // 总有效投注额(有效)
	AvgVetAount       string `gorm:"column:avg_vet_aount;not null;default:0;comment:笔均注单额(有效)" json:"avg_vet_aount"`        // 笔均注单额(有效)
	Ggr               string `gorm:"column:ggr;not null;default:0;comment:GGR指标" json:"ggr"`                                // GGR指标
	KillRate          string `gorm:"column:kill_rate;not null;default:0;comment:杀率" json:"kill_rate"`                       // 杀率
	UpdatedAt         int64  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                             // 更新时间
	CreatedAt         int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                             // 创建时间
	VaildTotalBillNum int64  `gorm:"column:vaild_total_bill_num;not null" json:"vaild_total_bill_num"`
}

// TableName FbDailyVenueReport's table name
func (*FbDailyVenueReport) TableName() string {
	return TableNameFbDailyVenueReport
}
