// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbLazadaOrder = "fb_lazada_orders"

// FbLazadaOrder mapped from table <fb_lazada_orders>
type FbLazadaOrder struct {
	OrderID              int64   `gorm:"column:order_id;primaryKey" json:"order_id"`
	OrderStatus          string  `gorm:"column:order_status" json:"order_status"`
	SmsStatus            string  `gorm:"column:sms_status" json:"sms_status"`
	BuyerID              string  `gorm:"column:buyer_id" json:"buyer_id"`
	BuyerPhoneNumber     string  `gorm:"column:buyer_phone_number" json:"buyer_phone_number"`
	PaidAmount           float64 `gorm:"column:paid_amount" json:"paid_amount"`
	PaidAt               int64   `gorm:"column:paid_at" json:"paid_at"`
	ExchangeCode         string  `gorm:"column:exchange_code" json:"exchange_code"`
	ExchangeAmount       float64 `gorm:"column:exchange_amount" json:"exchange_amount"`
	ExchangeStatus       string  `gorm:"column:exchange_status" json:"exchange_status"`
	ExchangerPhoneNumber string  `gorm:"column:exchanger_phone_number" json:"exchanger_phone_number"`
	ExchangerUsername    string  `gorm:"column:exchanger_username" json:"exchanger_username"`
	ExchangedAt          int64   `gorm:"column:exchanged_at" json:"exchanged_at"`
	Log                  string  `gorm:"column:log" json:"log"`
	CreatedAt            int64   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt            int64   `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName FbLazadaOrder's table name
func (*FbLazadaOrder) TableName() string {
	return TableNameFbLazadaOrder
}
