// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbPromoBlindboxBet = "fb_promo_blindbox_bet"

// FbPromoBlindboxBet 盲盒注单记录
type FbPromoBlindboxBet struct {
	BillNoHash     int64   `gorm:"column:bill_no_hash;primaryKey;comment:注单号hash" json:"bill_no_hash"`                         // 注单号hash
	BillNo         string  `gorm:"column:bill_no;not null;default:0;comment:平台唯一注单流水号" json:"bill_no"`                         // 平台唯一注单流水号
	PlatformID     string  `gorm:"column:platform_id;not null;default:0;comment:接口平台 如 AG MG" json:"platform_id"`              // 接口平台 如 AG MG
	PlatformName   string  `gorm:"column:platform_name;not null;comment:平台名称" json:"platform_name"`                            // 平台名称
	UID            string  `gorm:"column:uid;not null;default:0;comment:用户ID" json:"uid"`                                      // 用户ID
	Username       string  `gorm:"column:username;not null;comment:玩家账号" json:"username"`                                      // 玩家账号
	Phone          string  `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                             // 手机号
	ParentUID      string  `gorm:"column:parent_uid;not null;comment:上级uid" json:"parent_uid"`                                 // 上级uid
	ParentName     string  `gorm:"column:parent_name;not null;comment:上级代理" json:"parent_name"`                                // 上级代理
	GameClass      string  `gorm:"column:game_class;not null;default:1;comment:游戏类型" json:"game_class"`                        // 游戏类型
	GameName       string  `gorm:"column:game_name;not null;comment:第三方游戏名称" json:"game_name"`                                 // 第三方游戏名称
	GameCode       string  `gorm:"column:game_code;not null;comment:第三方游戏名称编码" json:"game_code"`                               // 第三方游戏名称编码
	ValidBetAmount float64 `gorm:"column:valid_bet_amount;not null;default:0.00;comment:有效投注金额(钱包币种)" json:"valid_bet_amount"` // 有效投注金额(钱包币种)
	BetTime        int64   `gorm:"column:bet_time;not null;comment:投注时间" json:"bet_time"`                                      // 投注时间
	State          int32   `gorm:"column:state;not null;comment:结算状态 0:下注确认(未结算) 1:已结算 2:会员取消 3:无效" json:"state"`              // 结算状态 0:下注确认(未结算) 1:已结算 2:会员取消 3:无效
}

// TableName FbPromoBlindboxBet's table name
func (*FbPromoBlindboxBet) TableName() string {
	return TableNameFbPromoBlindboxBet
}
