// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbReportMemberReg = "fb_report_member_reg"

// FbReportMemberReg 新增会员日报表
type FbReportMemberReg struct {
	ID                    int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                 // ID
	Day                   int32   `gorm:"column:day;not null;comment:年月日" json:"day"`                                                   // 年月日
	Reg                   int32   `gorm:"column:reg;not null;comment:新增注册数" json:"reg"`                                                 // 新增注册数
	RegDetail             string  `gorm:"column:reg_detail;not null;comment:注册来源渠道统计" json:"reg_detail"`                                // 注册来源渠道统计
	RegFirstDeposit       int32   `gorm:"column:reg_first_deposit;not null;comment:注册首存数" json:"reg_first_deposit"`                     // 注册首存数
	RegFirstDepositDetail string  `gorm:"column:reg_first_deposit_detail;not null;comment:注册首存明细" json:"reg_first_deposit_detail"`      // 注册首存明细
	ReportType            bool    `gorm:"column:report_type;not null;comment:报表类型，1日报、2周报、3月报" json:"report_type"`                      // 报表类型，1日报、2周报、3月报
	FirstDeposit          int32   `gorm:"column:first_deposit;not null;comment:首存" json:"first_deposit"`                                // 首存
	FirstDepositDetail    string  `gorm:"column:first_deposit_detail;not null;comment:首存明细" json:"first_deposit_detail"`                // 首存明细
	FirstDepositAmount    float64 `gorm:"column:first_deposit_amount;not null;default:0.00;comment:首存金额" json:"first_deposit_amount"`   // 首存金额
	SecondDeposit         int32   `gorm:"column:second_deposit;not null;comment:二存" json:"second_deposit"`                              // 二存
	SecondDepositAmount   float64 `gorm:"column:second_deposit_amount;not null;default:0.00;comment:二存金额" json:"second_deposit_amount"` // 二存金额
	ThirdDeposit          int32   `gorm:"column:third_deposit;not null;comment:三存" json:"third_deposit"`                                // 三存
	ThirdDepositAmount    float64 `gorm:"column:third_deposit_amount;not null;default:0.00;comment:三存金额" json:"third_deposit_amount"`   // 三存金额
	Bonus                 float64 `gorm:"column:bonus;not null;default:0.00;comment:礼金" json:"bonus"`                                   // 礼金
	BonusDetail           string  `gorm:"column:bonus_detail;not null;comment:礼金明细" json:"bonus_detail"`                                // 礼金明细
	CreatedAt             int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                    // 创建时间
}

// TableName FbReportMemberReg's table name
func (*FbReportMemberReg) TableName() string {
	return TableNameFbReportMemberReg
}
