// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbReportMemberTotal = "fb_report_member_total"

// FbReportMemberTotal 会员总报表
type FbReportMemberTotal struct {
	UID            int64   `gorm:"column:uid;primaryKey" json:"uid"`
	Phone          string  `gorm:"column:phone;not null;comment:手机号" json:"phone"`                       // 手机号
	Username       string  `gorm:"column:username;not null;comment:用户名" json:"username"`                 // 用户名
	ValidBetAmount float64 `gorm:"column:valid_bet_amount;not null;comment:投注额" json:"valid_bet_amount"` // 投注额
	SettleAmount   float64 `gorm:"column:settle_amount;not null;comment:派彩额" json:"settle_amount"`       // 派彩额
	Ggr            float64 `gorm:"column:ggr;not null;comment:GGR" json:"ggr"`                           // GGR
	DepositAmount  float64 `gorm:"column:deposit_amount;not null;comment:存款额" json:"deposit_amount"`     // 存款额
	WithdrawAmount float64 `gorm:"column:withdraw_amount;not null;comment:提款额" json:"withdraw_amount"`   // 提款额
	CreatedAt      int64   `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName FbReportMemberTotal's table name
func (*FbReportMemberTotal) TableName() string {
	return TableNameFbReportMemberTotal
}
