// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbReportProfit = "fb_report_profit"

// FbReportProfit 平台业绩日报表
type FbReportProfit struct {
	ID                 int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                // ID
	Day                int32   `gorm:"column:day;not null;comment:年月日" json:"day"`                                                  // 年月日
	Logged             int32   `gorm:"column:logged;not null;comment:登陆统计" json:"logged"`                                           // 登陆统计
	Kyc                int32   `gorm:"column:kyc;not null;comment:kyc统计" json:"kyc"`                                                // kyc统计
	Active             int32   `gorm:"column:active;not null;comment:活跃人数" json:"active"`                                           // 活跃人数
	DepositPeople      int32   `gorm:"column:deposit_people;not null;comment:充值人数" json:"deposit_people"`                           // 充值人数
	DepositAmount      float64 `gorm:"column:deposit_amount;not null;default:0.00;comment:总存款金额" json:"deposit_amount"`             // 总存款金额
	Deposits           int32   `gorm:"column:deposits;not null;comment:充值次数" json:"deposits"`                                       // 充值次数
	DepositSucceed     int32   `gorm:"column:deposit_succeed;not null;comment:充值成功次数" json:"deposit_succeed"`                       // 充值成功次数
	DepositSuccessRate float64 `gorm:"column:deposit_success_rate;not null;default:0.00;comment:充值成功率" json:"deposit_success_rate"` // 充值成功率
	DepositAvg         float64 `gorm:"column:deposit_avg;not null;default:0.00;comment:笔均充值金额" json:"deposit_avg"`                  // 笔均充值金额
	DepositFee         float64 `gorm:"column:deposit_fee;not null;default:0.00;comment:总充值手续" json:"deposit_fee"`                   // 总充值手续
	ReportType         bool    `gorm:"column:report_type;not null;comment:报表类型：1日报、2周报、3月报" json:"report_type"`                     // 报表类型：1日报、2周报、3月报
	WithdrawPeople     int32   `gorm:"column:withdraw_people;not null;comment:提现人数" json:"withdraw_people"`                         // 提现人数
	Withdraws          int32   `gorm:"column:withdraws;not null;comment:成功提现次数" json:"withdraws"`                                   // 成功提现次数
	WithdrawAmount     float64 `gorm:"column:withdraw_amount;not null;default:0.00;comment:总提现金额" json:"withdraw_amount"`           // 总提现金额
	WithdrawRemark     string  `gorm:"column:withdraw_remark;not null;comment:提现用时" json:"withdraw_remark"`                         // 提现用时
	DwDiff             float64 `gorm:"column:dw_diff;not null;default:0.00;comment:存提差" json:"dw_diff"`                             // 存提差
	Bets               int32   `gorm:"column:bets;not null;comment:总注单数" json:"bets"`                                               // 总注单数
	ValidBetAmount     float64 `gorm:"column:valid_bet_amount;not null;default:0.0000;comment:总有效投注额" json:"valid_bet_amount"`      // 总有效投注额
	BetAvg             float64 `gorm:"column:bet_avg;not null;default:0.0000;comment:笔均注单额" json:"bet_avg"`                         // 笔均注单额
	Ggr                float64 `gorm:"column:ggr;not null;default:0.0000;comment:GGR" json:"ggr"`                                   // GGR
	Rate               float64 `gorm:"column:rate;not null;default:0.00;comment:杀率" json:"rate"`                                    // 杀率
	BonusDue           float64 `gorm:"column:bonus_due;not null;default:0.0000;comment:应发礼金" json:"bonus_due"`                      // 应发礼金
	BonusReceived      float64 `gorm:"column:bonus_received;not null;default:0.0000;comment:实发礼金" json:"bonus_received"`            // 实发礼金
	Commission         float64 `gorm:"column:commission;not null;default:0.0000;comment:佣金" json:"commission"`                      // 佣金
	CreatedAt          int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                   // 创建时间
}

// TableName FbReportProfit's table name
func (*FbReportProfit) TableName() string {
	return TableNameFbReportProfit
}
