// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbSm = "fb_sms"

// FbSm mapped from table <fb_sms>
type FbSm struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name;not null" json:"name"`
	Config string `gorm:"column:config;not null" json:"config"`
	State  int32  `gorm:"column:state;not null;default:1;comment:1:开启 2:关闭" json:"state"` // 1:开启 2:关闭
}

// TableName FbSm's table name
func (*FbSm) TableName() string {
	return TableNameFbSm
}
