// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbTaskBonu = "fb_task_bonus"

// FbTaskBonu 任务领取记录表
type FbTaskBonu struct {
	ID         int64   `gorm:"column:id;primaryKey" json:"id"`
	UID        int64   `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                          // 用户ID
	Username   string  `gorm:"column:username;not null;comment:用户名" json:"username"`                 // 用户名
	ParentUID  string  `gorm:"column:parent_uid;not null;default:0;comment:上级UID" json:"parent_uid"` // 上级UID
	ParentName string  `gorm:"column:parent_name;not null;comment:上级用户名" json:"parent_name"`         // 上级用户名
	Pid        int64   `gorm:"column:pid;not null;comment:任务ID" json:"pid"`                          // 任务ID
	Name       string  `gorm:"column:name;not null" json:"name"`
	Ty         int32   `gorm:"column:ty;not null;comment:活动类型" json:"ty"`                                  // 活动类型
	Bonus      float64 `gorm:"column:bonus;not null;default:0.00;comment:活动奖金金额" json:"bonus"`             // 活动奖金金额
	State      int32   `gorm:"column:state;not null;default:1;comment:状态 1:已领取 2:待审核，3.审核拒绝" json:"state"` // 状态 1:已领取 2:待审核，3.审核拒绝
	CreatedAt  int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt  int64   `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                  // 更新时间
	ReviewName string  `gorm:"column:review_name;not null" json:"review_name"`
	ReviewAt   int64   `gorm:"column:review_at;not null" json:"review_at"`
	ReviewUID  int64   `gorm:"column:review_uid;not null;comment:审核人uid" json:"review_uid"` // 审核人uid
	Remark     string  `gorm:"column:remark;not null;comment:备注" json:"remark"`             // 备注
	Day        int32   `gorm:"column:day;not null" json:"day"`
	ReceiveAt  int64   `gorm:"column:receive_at;not null" json:"receive_at"`
	Phone      string  `gorm:"column:phone;not null" json:"phone"`
	UniqueID   string  `gorm:"column:unique_id;not null;comment:唯一ID" json:"unique_id"` // 唯一ID
}

// TableName FbTaskBonu's table name
func (*FbTaskBonu) TableName() string {
	return TableNameFbTaskBonu
}
