// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbTaskList = "fb_task_list"

// FbTaskList 任务列表
type FbTaskList struct {
	ID           int64  `gorm:"column:id;primaryKey" json:"id"`
	Name         string `gorm:"column:name;not null;comment:任务名称英文名称" json:"name"`                                          // 任务名称英文名称
	TaskCategory int32  `gorm:"column:task_category;not null;default:6;comment:任务大类 1新手任务，2日常任务" json:"task_category"`      // 任务大类 1新手任务，2日常任务
	Ty           int32  `gorm:"column:ty;not null;default:6;comment:任务类型" json:"ty"`                                        // 任务类型
	State        int32  `gorm:"column:state;not null;default:1;comment:状态 1开启 2关闭 3未开启 4已删除" json:"state"`                  // 状态 1开启 2关闭 3未开启 4已删除
	Config       string `gorm:"column:config;not null;comment:活动配置" json:"config"`                                          // 活动配置
	StartAt      int64  `gorm:"column:start_at;not null;comment:开始时间" json:"start_at"`                                      // 开始时间
	EndAt        int64  `gorm:"column:end_at;not null;comment:结束时间" json:"end_at"`                                          // 结束时间
	Multiple     string `gorm:"column:multiple;not null;default:1.00;comment:流水倍数" json:"multiple"`                         // 流水倍数
	Recommend    int32  `gorm:"column:recommend;not null;default:2;comment:推荐状态 1推荐 2不推荐" json:"recommend"`                 // 推荐状态 1推荐 2不推荐
	Sort         int32  `gorm:"column:sort;not null;default:1000;comment:英语排序" json:"sort"`                                 // 英语排序
	Images       string `gorm:"column:images;not null;comment:图片(包含背景图和logo)" json:"images"`                                // 图片(包含背景图和logo)
	Summary      string `gorm:"column:summary;not null;comment:简介" json:"summary"`                                          // 简介
	DisplayType  int32  `gorm:"column:display_type;not null;default:1;comment:// 展示方式 1:内置页面 2:跳转外部链接" json:"display_type"` // // 展示方式 1:内置页面 2:跳转外部链接
	CreatedAt    int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                  // 创建时间
	CreatedUID   int64  `gorm:"column:created_uid;not null;comment:创建人uid" json:"created_uid"`                              // 创建人uid
	CreatedName  string `gorm:"column:created_name;not null;comment:创建人名" json:"created_name"`                              // 创建人名
	UpdatedAt    int64  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`                                  // 修改时间
	UpdatedUID   int64  `gorm:"column:updated_uid;not null;comment:修改人uid" json:"updated_uid"`                              // 修改人uid
	UpdatedName  string `gorm:"column:updated_name;not null;comment:修改人名" json:"updated_name"`                              // 修改人名
	NameTa       string `gorm:"column:name_ta;not null" json:"name_ta"`
	SummaryTa    string `gorm:"column:summary_ta;not null" json:"summary_ta"`
	Vip          int32  `gorm:"column:vip;not null" json:"vip"`
	VipLevel     string `gorm:"column:vip_level;not null" json:"vip_level"`
}

// TableName FbTaskList's table name
func (*FbTaskList) TableName() string {
	return TableNameFbTaskList
}
