// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFbVipXpLog = "fb_vip_xp_log"

// FbVipXpLog 用户vip成长值日志表
type FbVipXpLog struct {
	ID              int64   `gorm:"column:id;primaryKey" json:"id"`
	UID             int64   `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                               // 用户ID
	Username        string  `gorm:"column:username;not null;comment:用户名" json:"username"`                      // 用户名
	FormerXp        float64 `gorm:"column:former_xp;not null;default:0.00;comment:之前的xp" json:"former_xp"`     // 之前的xp
	GetXp           float64 `gorm:"column:get_xp;not null;default:0.00;comment:获取到的xp" json:"get_xp"`          // 获取到的xp
	CurrentXp       float64 `gorm:"column:current_xp;not null;default:0.00;comment:当前xp" json:"current_xp"`    // 当前xp
	BetAmount       float64 `gorm:"column:bet_amount;not null;default:0.00;comment:新增的投注金额" json:"bet_amount"` // 新增的投注金额
	FormerVipLevel  int32   `gorm:"column:former_vip_level;not null;comment:之前的vip等级" json:"former_vip_level"` // 之前的vip等级
	CurrentVipLevel int32   `gorm:"column:current_vip_level;not null;comment:当前ip等级" json:"current_vip_level"` // 当前ip等级
	CreatedAt       int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                 // 创建时间
	UpdatedAt       int64   `gorm:"column:updated_at;not null;comment:维护时间" json:"updated_at"`                 // 维护时间
	ReviewAt        int64   `gorm:"column:review_at;not null;comment:审核时间" json:"review_at"`                   // 审核时间
	ReviewUID       int64   `gorm:"column:review_uid;not null;comment:审核人uid" json:"review_uid"`               // 审核人uid
	ReviewName      string  `gorm:"column:review_name;not null;comment:审核人" json:"review_name"`                // 审核人
	Remark          string  `gorm:"column:remark;not null;comment:审核备注" json:"remark"`                         // 审核备注
}

// TableName FbVipXpLog's table name
func (*FbVipXpLog) TableName() string {
	return TableNameFbVipXpLog
}
